"""Update models for E2E flow

Revision ID: a67febbe6a27
Revises: 0001_initial
Create Date: 2026-08-18 23:10:34.469015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a67febbe6a27'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_roles', sa.Column('is_custom', sa.Boolean(), nullable=False))
    op.add_column('job_roles', sa.Column('mapped_to_role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'job_roles', 'job_roles', ['mapped_to_role_id'], ['role_id'])
    op.add_column('mock_sessions', sa.Column('mode', sa.String(length=50), nullable=False))
    op.add_column('mock_sessions', sa.Column('question_count', sa.Integer(), nullable=False))
    op.add_column('mock_sessions', sa.Column('tech_stacks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mock_sessions', sa.Column('overall_score', sa.Float(), nullable=True))
    op.drop_constraint('scores_answer_id_key', 'scores', type_='unique')
    op.drop_index('ix_scores_answer_id', table_name='scores')
    op.create_index(op.f('ix_scores_answer_id'), 'scores', ['answer_id'], unique=True)
    op.add_column('session_questions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('session_questions', sa.Column('time_spent_seconds', sa.Integer(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('session_questions', 'time_spent_seconds')
    op.drop_column('session_questions', 'status')
    op.drop_index(op.f('ix_scores_answer_id'), table_name='scores')
    op.create_index('ix_scores_answer_id', 'scores', ['answer_id'], unique=False)
    op.create_unique_constraint('scores_answer_id_key', 'scores', ['answer_id'])
    op.drop_column('mock_sessions', 'overall_score')
    op.drop_column('mock_sessions', 'tech_stacks')
    op.drop_column('mock_sessions', 'question_count')
    op.drop_column('mock_sessions', 'mode')
    op.drop_constraint(None, 'job_roles', type_='foreignkey')
    op.drop_column('job_roles', 'mapped_to_role_id')
    op.drop_column('job_roles', 'is_custom')
    # ### end Alembic commands ###
